"use client";

import React from "react";

/**
 * High-quality 24x24 Pixel Art Icons for Blog Posts.
 * Symbols:
 * X: Primary Color (currentColor)
 * S: Shadow/Subtle (60% opacity)
 * H: Highlight (80% opacity)
 * L: Low-opacity Detail (30% opacity)
 */
const ICON_DESIGNS = {
    performance: [
        "........................",
        "........................",
        "............XXXX........",
        "...........XXXXX........",
        "..........XXXXXX........",
        ".........XXXXXXX........",
        "........XXXXXXXX........",
        ".......XXXXXXXXX........",
        "......XXXXXXXXXX........",
        ".....XXXXXXXXXXX........",
        "....XXXXXXXXXXXX........",
        "...XXXXXXXXXXXXX........",
        "...XXXXXXXXXXXXS........",
        ".......XXXXXXXXSS.......",
        "......XXXXXXXSSS........",
        ".....XXXXXXSSSS.........",
        "....XXXXXSSSS...........",
        "...XXXXSSSS.............",
        "..XXXSSSS...............",
        ".XXSSS..................",
        "XSS.....................",
        "........................",
        "........................",
        "........................",
    ],
    ar: [
        "........................",
        "........................",
        "....XXXXXXXXXXXXXXXX....",
        "...XXXXXXXXXXXXXXXXXX...",
        "..XXXXXXXXXXXXXXXXXXXX..",
        "..XXHHHHHHHHHHHHHHSSXX..",
        "..XHHHHHHHHHHHHHHHSSXX..",
        "..XHH..XXXXXXXXXX..SXX..",
        "..XHH.XXXXXXXXXXXX.SXX..",
        "..XHH.XX........XX.SXX..",
        "..XHH.XX........XX.SXX..",
        "..XHH.XX........XX.SXX..",
        "..XHH.XXXXXXXXXXXX.SXX..",
        "..XHH..XXXXXXXXXX..SXX..",
        "..XHHHHHHHHHHHHHHHSSXX..",
        "..XXSSSSSSSSSSSSSSSSSXX..",
        "..XXXXXXXXXXXXXXXXXXXX..",
        "...XXXXXXXXXXXXXXXXXX...",
        "....XXXXXXXXXXXXXXXX....",
        "........................",
        ".........XXXXXX.........",
        ".......XXXXXXXXXX.......",
        "......XXXXXXXXXXXX......",
        "........................",
    ],
    telegram: [
        "........................",
        "................X.......",
        "...............XX.......",
        "..............XXX.......",
        ".............XXXX.......",
        "............XXXXX.......",
        "...........XXXXXX.......",
        "..........XXXXXXX.......",
        ".........XXXXXXXX.......",
        "........XXXXXXXXX.......",
        ".......XXXXXXXXXX.......",
        "......XXXXXXXXXXX.......",
        ".....XXXXXXXXXXXX.......",
        "....XXXXXXXXXXXXX.......",
        "...XXXXXXXXXXXXXX.......",
        "..XXXXXXXXXXXXXXX.......",
        "XXXXXXXXXXXXXXXXXXXXX...",
        "..XXXXXXXXXXXXXXX.......",
        "...XXXXXXXXXXXXXX.......",
        "....XXXXXXXXXXXXX.......",
        ".....XXXXXXXXXXXX.......",
        "......XXXXXXXXXXX.......",
        ".......XXXXXXXXXX.......",
        "........XXXXXXXXX.......",
    ],
    agent: [
        "........................",
        ".......XXXXXXXXXX.......",
        ".....XXXXXXXXXXXXXX.....",
        "....XXXXXXXXXXXXXXXX....",
        "...XXXXXXXXXXXXXXXXXX...",
        "..XXXXXXXXXXXXXXXXXXXX..",
        "..XXXXHHXXXXXXXXHHXXXX..",
        ".XXXXXHHXXXXXXXXHHXXXXX.",
        ".XXXXXHHXXXXXXXXHHXXXXX.",
        ".XXXXXHHXXXXXXXXHHXXXXX.",
        ".XXXXXXXSXXXXXXSXXXXXXX.",
        ".XXXXXXXXXXXXXXXXXXXXXX.",
        ".XXXXXXSXXXXXXXXSXXXXXX.",
        "..XXXXSXXXXXXXXXXSXXXX..",
        "..XXXXXXSSSSSSSSXXXXXX..",
        "...XXXXXXXXXXXXXXXXXX...",
        "....XXXXXXXXXXXXXXXX....",
        ".....XXXXXXXXXXXXXX.....",
        ".......XXXXXXXXXX.......",
        "..........XXXX..........",
        ".........XXXXXX.........",
        ".......XXXXXXXXXX.......",
        "......XXXXXXXXXXXX......",
        "........................",
    ],
    database: [
        "........................",
        ".....XXXXXXXXXXXXXX.....",
        "....XXXXXXXXXXXXXXXX....",
        "...XXHHHHHHHHHHHHSSXX...",
        "..XXHHHHHHHHHHHHHHSSXX..",
        "..XXSSSSSSSSSSSSSSSSXX..",
        "..XX................XX..",
        "..XXHHHHHHHHHHHHHHSSXX..",
        "..XXHHHHHHHHHHHHHHSSXX..",
        "..XXSSSSSSSSSSSSSSSSXX..",
        "..XX................XX..",
        "..XXHHHHHHHHHHHHHHSSXX..",
        "..XXHHHHHHHHHHHHHHSSXX..",
        "..XXSSSSSSSSSSSSSSSSXX..",
        "..XX................XX..",
        "..XXHHHHHHHHHHHHHHSSXX..",
        "..XXHHHHHHHHHHHHHHSSXX..",
        "..XXSSSSSSSSSSSSSSSSXX..",
        "..XX................XX..",
        "..XXHHHHHHHHHHHHHHSSXX..",
        "..XXHHHHHHHHHHHHHHSSXX..",
        "..XXSSSSSSSSSSSSSSSSXX..",
        "....XXXXXXXXXXXXXXXX....",
        ".....XXXXXXXXXXXXXX.....",
    ],
    vision: [
        "........................",
        ".........XXXXXX.........",
        "......XXXXXXXXXXXX......",
        "....XXXXXXXXXXXXXXXX....",
        "...XXXXXXXXXXXXXXXXXX...",
        "..XXXXXXHHHHHHXXXXXXSS..",
        "..XXXXXHHHHHHHHXXXXXSS..",
        ".XXXXXHHHHHHHHHHXXXXXSS.",
        ".XXXXHHHH..XX..HHHHXXSS.",
        ".XXXXHHH..XXXX..HHHXXSS.",
        ".XXXXHH..XXXXXX..HHXXSS.",
        ".XXXXHH..XXXXXX..HHXXSS.",
        ".XXXXHHH..XXXX..HHHXXSS.",
        ".XXXXHHHH..XX..HHHHXXSS.",
        ".XXXXXHHHHHHHHHHXXXXXSS.",
        ".XXXXXHHHHHHHHHHXXXXXSS.",
        "..XXXXXHHHHHHHHXXXXXSS..",
        "..XXXXXXHHHHHHXXXXXXSS..",
        "...XXXXXXXXXXXXXXXXXX...",
        "....XXXXXXXXXXXXXXXX....",
        "......XXXXXXXXXXXX......",
        ".........XXXXXX.........",
        "........................",
        "........................",
    ],
    golf: [
        "........................",
        ".........XXXXXX.........",
        "......XXXXXXXXXXXX......",
        "....XXXXHHHHHHHHXXXX....",
        "...XXXXHHHHHHHHHHXXXX...",
        "..XXXXHHHHHHHHHHHHXXXX..",
        "..XXXXHHHHHLHLHHHHXXXX..",
        ".XXXXHHHHHLHLHLHHHHXXXX.",
        ".XXXXHHHHHHLLLHHHHHXXXX.",
        ".XXXXHHHHHHLLLHHHHHXXXX.",
        ".XXXXHHHHHLHLHLHHHHXXXX.",
        "..XXXXHHHHHLHLHHHHXXXX..",
        "..XXXXHHHHHHHHHHHHXXXX..",
        "...XXXXHHHHHHHHHHXXXX...",
        "....XXXXHHHHHHHHXXXX....",
        "......XXXXXXXXXXXX......",
        ".........XXXXXX.........",
        "..........XXXX..........",
        "..........XXXX..........",
        ".........XXXXXX.........",
        "........XXXXXXXX........",
        ".......XXXXXXXXXX.......",
        "......XXXXXXXXXXXX......",
        "........................",
    ],
    video: [
        "XXXXXXXXXXXXXXXXXXXXXXXX",
        "XLLLLLLLLLLLLLLLLLLLLLLX",
        "XLLLLLLLLLLLLLLLLLLLLLLX",
        "XLLXXXXXXXXXXXXXXXXXXLLX",
        "XLLXHHHHHHHHHHHHHHSSXLLX",
        "XLLXHHHHHHHHHHHHHHSSXLLX",
        "XLLXHH..XXXXXXXX..SSXLLX",
        "XLLXHH..X......X..SSXLLX",
        "XLLXHH..X..XX..X..SSXLLX",
        "XLLXHH..X..XX..X..SSXLLX",
        "XLLXHH..X......X..SSXLLX",
        "XLLXHH..XXXXXXXX..SSXLLX",
        "XLLXHH............SSXLLX",
        "XLLXHH..XXXXXXXX..SSXLLX",
        "XLLXHH..X......X..SSXLLX",
        "XLLXHH..X..XX..X..SSXLLX",
        "XLLXHH..X..XX..X..SSXLLX",
        "XLLXHH..X......X..SSXLLX",
        "XLLXHH..XXXXXXXX..SSXLLX",
        "XLLXSSSSSSSSSSSSSSSSXLLX",
        "XLLXXXXXXXXXXXXXXXXXXLLX",
        "XLLLLLLLLLLLLLLLLLLLLLLX",
        "XLLLLLLLLLLLLLLLLLLLLLLX",
        "XXXXXXXXXXXXXXXXXXXXXXXX",
    ],
    math: [
        "........................",
        "....XXXXXXXXXXXXXXX.....",
        "....XXXXXXXXXXXXXXXX....",
        "....XXHHHHHHHHHHHHHH....",
        "....XXHHHHHHHHHHHHHH....",
        "....XXSSSSSXXXXXXXXX....",
        "...........XXXXXXX......",
        "..........XXXXXXX.......",
        ".........XXXXXXX........",
        "........XXXXXXX.........",
        ".......XXXXXXX..........",
        "......XXXXXXX...........",
        ".....XXXXXXX............",
        "....XXXXXXX.............",
        "....XXXXXXX.............",
        "....XXSSSSSXXXXXXXXX....",
        "....XXHHHHHHHHHHHHHH....",
        "....XXHHHHHHHHHHHHHH....",
        "....XXXXXXXXXXXXXXXX....",
        "....XXXXXXXXXXXXXXX.....",
        "........................",
        "........................",
        "........................",
        "........................",
    ],
    research: [
        "........................",
        ".......XXXXXXXX.........",
        ".....XXXXXXXXXXXX.......",
        "....XXXXXXXXXXXXXX......",
        "...XXXXHHHHHHHHXXXX.....",
        "...XXXHHHHHHHHHHXXX.....",
        "..XXXXHHHHHHHHHHXXXX....",
        "..XXXXHHHHHHHHHHXXXX....",
        "..XXXXHHHLHLHHHHXXXX....",
        "..XXXXHHHLHLHHHHXXXX....",
        "...XXXHHHHHHHHHHXXX.....",
        "...XXXXHHHHHHHHXXXX.....",
        "....XXXXXXXXXXXXXX......",
        ".....XXXXXXXXXXXXS......",
        ".......XXXXXXXSS........",
        "............SSS.........",
        "...........SSS..........",
        "..........SSS...........",
        ".........SSS............",
        "........SSS.............",
        ".......SSS..............",
        "......SSS...............",
        ".....SSS................",
        "....SSS.................",
    ],
    motion: [
        "........................",
        "........................",
        "..................XXXX..",
        "...............XXXXXXSS.",
        "............XXXXXXXXSS..",
        ".........XXXXXXXXHHSS...",
        "......XXXXXXXXHHHHS.....",
        "....XXXXXXXHHHHHS.......",
        "...XXXXXXHHHHHS.........",
        "..XXXXXHHHHHS...........",
        "..XXXXHHHHSS............",
        ".XXXXHHHHSS.............",
        ".XXXXHHHSS..............",
        ".XXXXHHSS...............",
        ".XXXXHSS................",
        "..XXXSS.................",
        "..XXSS..................",
        "...XSS..................",
        "....SS..................",
        ".....S..................",
        "........................",
        "........................",
        "........................",
        "........................",
    ],
};

const SLUG_TO_ICON: Record<string, keyof typeof ICON_DESIGNS> = {
    "aki-performance-and-scalability": "performance",
    "ar-menu": "ar",
    "building-ai-companion-telegram": "telegram",
    "conversational-ai-agent-techniques": "agent",
    "dynamodb-cmdline": "database",
    "enph-353-cnn": "vision",
    "golf-chatbot": "golf",
    "latent-video-diffusion": "video",
    "rlhf-llm-math": "math",
    "swing-analysis": "motion",
    "tavily-deep-research": "research",
};

export function BlogIcon({
    slug,
    size = 48,
    className = ""
}: {
    slug: string;
    size?: number;
    className?: string;
}) {
    const iconKey = SLUG_TO_ICON[slug] || "agent";
    const grid = ICON_DESIGNS[iconKey];

    return (
        <svg
            width={size}
            height={size}
            viewBox="0 0 24 24"
            className={`fill-current ${className}`}
            aria-label={`Icon for ${slug}`}
        >
            {grid.map((row, y) => (
                row.split("").map((char, x) => {
                    let opacity = 1;
                    if (char === "S") opacity = 0.5;
                    if (char === "H") opacity = 0.8;
                    if (char === "L") opacity = 0.2;
                    
                    return char !== "." ? (
                        <rect
                            key={`${x}-${y}`}
                            x={x}
                            y={y}
                            width="1"
                            height="1"
                            shapeRendering="crispEdges"
                            style={{ opacity }}
                        />
                    ) : null;
                })
            ))}
        </svg>
    );
}
